name: ESLintã‚¨ãƒ©ãƒ¼ãƒã‚§ãƒƒã‚¯ï¼‹è‡ªå‹•ä¿®æ­£
on:
  push:
    paths:
      - '**.js'
      - '**.ts'
      - '**.vue'
      - '.eslintrc.yml'

jobs:
  build:
    name: ESLintãƒã‚§ãƒƒã‚¯
    runs-on: ubuntu-latest
    steps:
      - name: ãƒ–ãƒ©ãƒ³ãƒã‚’ãƒã‚§ãƒƒã‚¯ã‚¢ã‚¦ãƒˆ
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Node.jsã®ã‚»ãƒƒãƒˆã‚¢ãƒƒãƒ—
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: ãƒ‘ãƒƒã‚±ãƒ¼ã‚¸ã‚¤ãƒ³ã‚¹ãƒˆãƒ¼ãƒ«
        run: yarn install
      - name: ESLintãƒã‚§ãƒƒã‚¯å®Ÿè¡Œ
        run: yarn lintjs:fix --max-warnings 0
      - name: ESLintã®è‡ªå‹•ä¿®æ­£åˆ†ã‚’Push
        run: |
          git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          if (git diff --shortstat | grep '[0-9]'); then \
            git add .; \
            git commit -m "ğŸ‘• Fixed auto-fixable ESLint errors by github-actions"; \
            git push origin HEAD:${GITHUB_REF}; \
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

